"""init schema

Revision ID: ad3a61e7ef27
Revises: 
Create Date: 2025-12-24 00:33:20.520893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad3a61e7ef27'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cargoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender', sa.String(), nullable=False),
    sa.Column('recipient', sa.String(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'driver', name='role_enum_new'), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('trucks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plate_number', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('capacity_kg', sa.Integer(), nullable=False),
    sa.Column('volume_m3', sa.Integer(), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cargo_id', sa.Integer(), nullable=False),
    sa.Column('to_location', sa.String(), nullable=False),
    sa.Column('distance_km', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('estimated_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('status', sa.Enum('queued', 'assigned', 'completed', name='orderstatus'), nullable=False),
    sa.Column('truck_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cargo_id'], ['cargoes.id'], ),
    sa.ForeignKeyConstraint(['truck_id'], ['trucks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shipments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cargo_id', sa.Integer(), nullable=False),
    sa.Column('truck_id', sa.Integer(), nullable=False),
    sa.Column('from_location', sa.String(), nullable=False),
    sa.Column('to_location', sa.String(), nullable=False),
    sa.Column('pickup_date', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('delivered_date', sa.DateTime(), nullable=True),
    sa.Column('driver_deriver', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('waiting', 'on_way', 'delivered', name='deliverystatus'), nullable=False),
    sa.ForeignKeyConstraint(['cargo_id'], ['cargoes.id'], ),
    sa.ForeignKeyConstraint(['driver_deriver'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['truck_id'], ['trucks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shipments')
    op.drop_table('orders')
    op.drop_table('trucks')
    op.drop_table('employee')
    op.drop_table('cargoes')
    # ### end Alembic commands ###
