"""add roleenum type

Revision ID: d09f8ee8452e
Revises: 09dedf4dac42
Create Date: 2025-12-24 04:23:47.139236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd09f8ee8452e'
down_revision: Union[str, Sequence[str], None] = '09dedf4dac42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee', 'role',
               existing_type=postgresql.ENUM('admin', 'driver', name='role_enum_new'),
               type_=sa.Enum('admin', 'driver', name='roleenum'),
               existing_nullable=False)
    op.drop_constraint(op.f('shipments_driver_deriver_fkey'), 'shipments', type_='foreignkey')
    op.create_foreign_key(None, 'shipments', 'employee', ['driver_deriver'], ['id'])
    op.drop_column('shipments', 'driver_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipments', sa.Column('driver_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'shipments', type_='foreignkey')
    op.create_foreign_key(op.f('shipments_driver_deriver_fkey'), 'shipments', 'employee', ['driver_id'], ['id'])
    op.alter_column('employee', 'role',
               existing_type=sa.Enum('admin', 'driver', name='roleenum'),
               type_=postgresql.ENUM('admin', 'driver', name='role_enum_new'),
               existing_nullable=False)
    # ### end Alembic commands ###
